### PR TITLE
Adds parameter for namespace-specific linting

### PR DESCRIPTION
**Pull request by filipmazurek**
This adds the ability for users to specify their project id for namespace-specific linting. This feature was added as part of GitLab 13.6. I was using gll for my projects and since I'm using a lot of local include statements, this would help me out a lot!

The documentation for this api call can be found here: [validate yaml with namespace](https://docs.gitlab.com/ee/api/lint.html#validate-a-ci-yaml-configuration-with-a-namespace)

Unfortunately the response to this new endpoint returns with a "valid" field rather than a "status" field, which adds some extra complexity. I have my solution below, but I'm open to changing it.

Additionally, I added the parameter where I thought it would make sense (by the domain), but I'm happy to move this elsewhere.

### CODE REVIEW

**Comment by lriesebos** [comment]
@elijah-roberts this is also a feature I am interested in. Please let us know what your thoughts are!

**Comment by elijah-roberts** [comment]
@filipmazurek  Looks great thank you for adding this. I just updated this project to add some basic tests... would you mind adding a couple tests for successful validation, and error validation for the new response type?

**Comment by elijah-roberts** [comment]
I also just pulled in the pre-commit hook @mick352  added... can you update your readme changes to resolve conflicts, and add your new flag to the readme pre-commit hook example?

**Comment by filipmazurek** [comment]
@elijah-roberts Just pushed all the changes! Updated the readme to include the project flag in example and added to the tests

**Review by elijah-roberts — APPROVED** [review]

**Pull request merged**
